server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:productdb
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
